### ISSUE TITLE
您好！我看您的jsmind引入了bootstrap。

### ISSUE THREAD

**Issue by zhangxiaoda007** [hanxiaomax/WordPowerMadeEasy#2]
我想在jsmind的topic中引入element-ui的popover，可是点击后没有任何反应，我想请问一下您在引入bootstrap是如何调整的呢？ 我是像下面这样直接引用的;
`<script type="text/javascript">
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
import Vue from 'vue'
import jsMind from 'jsmind';export default {
    name:'zhang',
    data() {
        return{
          mind: {
            "meta":{
                "name":"demo",
                "author":"hizzgdev@163.com",
                "version":"0.2",
            },
            "format":"node_array",
            "data":[
                {"id":"root","isroot":true,"topic":"我是根节点"},
                {"id":"sub1","parentid":"root","topic":"<el-popover placement='bottom' title='标题' width='200' trigger='click' content='这是一段内容,这是一段内容,这是一段内容,这是一段内容。'><el-button slot='reference'>click 激活</el-button></el-popover>"},`

**Comment by hanxiaomax** [comment]
您好，我不太了解element-ui，bootstrap的popover需要用js激活一下，其他的地方没有做特殊处理。
http://www.runoob.com/bootstrap/bootstrap-popover-plugin.html
（你试试把点击修改为hover看看可不可以）

或者，你可以到jsmind的[repo](https://github.com/hizzgdev/jsmind)去问一下作者

**Comment by zhangxiaoda007** [comment]
谢谢您的回复，我想知道您所说的用js激活一下，是使用jquery吗？

**Comment by hanxiaomax** [comment]
你看下我发的链接里面的例程

**Comment by zhangxiaoda007** [comment]
恩恩，看了，试了一下，我这边似乎不行，我使用的是vue框架
